#!/bin/bash
set -x

OI=/var/lib/openinfoman
USERNAME=oi
BASEX=$OI/bin/basex

$BASEX -Vc 'create database provider_directory'

adduser --system $USERNAME
addgroup $USERNAME
chown -R $USERNAME:$USERNAME $OI
chmod +s /usr/local/bin/oi-install-repos
chmod +s /usr/local/bin/oi-start
chmod +s /usr/local/bin/oi-log
chmod +s /usr/local/bin/oi-stop





REPOS=("csd_base_library.xqm" "csd_base_library_updating.xqm"   "csd_base_stored_queries.xqm"  "csd_document_manager.xqm"  "csd_load_sample_directories.xqm"  "csd_query_updated_services.xqm"  "csd_poll_service_directories.xqm"  "csd_local_services_cache.xqm"  "csd_merge_cached_services.xqm"  "csr_processor.xqm"  "svs_load_shared_value_sets.xqm"  "csd_webapp_config.xqm")


$BASEX -Vc "REPO INSTALL http://files.basex.org/modules/expath/functx-1.0.xar"

for REPO in ${REPOS[@]}
do
   INST="REPO INSTALL ${OI}/repo-src/${REPO}"
   $BASEX -Vc "${INST}"
done

chown -R $USERNAME:$USERNAME $OI


