#!/bin/bash
set -x

. /usr/share/debconf/confmodule

WGET=/usr/bin/wget
UNZIP=/usr/bin/unzip
OI=/var/lib/openinfoman
USERNAME=oi
BASEX=$OI/bin/basex

TMP=/tmp/openinfoman-basex
mkdir -p "${TMP}"

$WGET http://files.basex.org/releases/8.3.1/BaseX831.zip -O ${TMP}/BaseX.zip
$UNZIP -o -d ${TMP} ${TMP}/BaseX.zip


cp $TMP/basex/BaseX.jar $OI
DIRS=("bin" "etc" "lib" "webapp/dba")
for DIR in ${DIRS[@]}
do
    mkdir -p $OI/$DIR
    cp -R $TMP/basex/$DIR/* $OI/$DIR
done


$BASEX -Vc "list provider_directory" > /dev/null
if [ $? -eq 0 ]; then
    echo "BaseX Database provider_directory exists\n"
else
    echo "BaseX Database provider_directory does not exist\n"
    $BASEX -Vc 'create database provider_directory'
fi


chown -R $USERNAME:$USERNAME $OI
chmod +s /usr/bin/oi-log




REPOS=("csd_webapp_ui.xqm" "csd_base_library.xqm" "csd_base_library_updating.xqm"   "csd_base_stored_queries.xqm"  "csd_document_manager.xqm"  "csd_load_sample_directories.xqm"  "csd_query_updated_services.xqm"  "csd_poll_service_directories.xqm"  "csd_local_services_cache.xqm"  "csd_merge_cached_services.xqm"  "csr_processor.xqm"  "svs_load_shared_value_sets.xqm"  )
#excluding "csd_webapp_config.xqm"

mkdir -p $OI/repo-src
GENERATED="$OI/repo-src/generated_openinfoman_webconfig.xqm"
db_input high openinfoman/baseurl || true
db_go || true
db_get openinfoman/baseurl || true
BASEURL="$RET"

db_input high openinfoman/dbname || true
db_go || true
db_get openinfoman/dbname || true
DBNAME="$RET"
echo "module namespace csd_webconf = 'https://github.com/openhie/openinfoman/csd_webconf';
declare variable \$csd_webconf:db :=  '$DBNAME';
declare variable \$csd_webconf:baseurl :=  '$BASEURL';
declare variable \$csd_webconf:remote_services := ();
" > $OI/repo-src/generated_openinfoman_webconfig.xqm


$BASEX -Vc "REPO INSTALL http://files.basex.org/modules/expath/functx-1.0.xar"
$BASEX -Vc "REPO DELETE https://github.com/openhie/openinfoman/csd_webconf"  2> /dev/null || true
$BASEX -Vc "REPO INSTALL $GENERATED"


for REPO in ${REPOS[@]}
do
   INST="REPO INSTALL ${OI}/repo-src/${REPO}"
   $BASEX -Vc "${INST}"
done

chown -R $USERNAME:$USERNAME $OI

service openinfoman start || true

sleep 10


$WGET --no-check-certificate http://localhost:8984/CSD/storedFunctions/init -O /dev/null || true
$WGET --no-check-certificate http://localhost:8984/CSD/storedFunctions/reload -O /dev/null || true
$WGET --no-check-certificate http://localhost:8984/CSD/SVS/initSharedValueSet/init -O /dev/null || true


SVSS=("1.3.6.1.4.1.21367.200.101" "1.3.6.1.4.1.21367.200.102" "1.3.6.1.4.1.21367.200.103" "1.3.6.1.4.1.21367.200.104" "1.3.6.1.4.1.21367.200.105" "1.3.6.1.4.1.21367.200.106" "1.3.6.1.4.1.21367.200.108" "1.3.6.1.4.1.21367.200.109" "1.3.6.1.4.1.21367.200.110" "2.25.1098910207106778371035457739371181056504702027035" "2.25.17331675369518445540420660603637128875763657" "2.25.18630021159349753613449707959296853730613166189051" "2.25.259359036081944859901459759453974543442705863430576" "2.25.265608663818616228188834890512310231251363785626032" "2.25.309768652999692686176651983274504471835.999.400" "2.25.309768652999692686176651983274504471835.999.401" "2.25.309768652999692686176651983274504471835.999.402" "2.25.309768652999692686176651983274504471835.999.403" "2.25.309768652999692686176651983274504471835.999.404" "2.25.309768652999692686176651983274504471835.999.405" "2.25.309768652999692686176651983274504471835.999.406" "2.25.9830357893067925519626800209704957770712560" )

for SVS in ${SVSS[@]}
do
    $WGET --no-check-certificate http://localhost:8984/CSD/SVS/initSharedValueSet/svs/$SVS/load -O /dev/null || true
done
