#!/bin/bash
set -x
ACTION="$1"
VERSION="$2"

USERNAME=oi
HOME=/home/$USERNAME
USERADD=/usr/sbin/useradd
ADDGROUP=/usr/sbin/addgroup
ADDUSER=/usr/sbin/adduser
WGET=/usr/bin/wget
UNZIP=/usr/bin/unzip
OI=/var/lib/openinfoman


TMP=/tmp/openinfoman-basex
mkdir -p "${TMP}"
rm -fr ${TMP}/*

service openinfoman stop || true


install_basex() {
    $WGET http://files.basex.org/releases/8.5.2/BaseX852.zip -O ${TMP}/BaseX.zip
    $UNZIP -o -d ${TMP} ${TMP}/BaseX.zip

    cp $TMP/basex/BaseX.jar $OI
    DIRS=("bin" "etc" "lib" "webapp/dba")
    for DIR in ${DIRS[@]}
    do
	mkdir -p $OI/$DIR
	cp -R $TMP/basex/$DIR/* $OI/$DIR
    done
}

do_user() {
	if ! getent group $USERNAME >/dev/null; then
	    echo "Creating group $USERNAME"
	    $ADDGROUP --quiet --system $USERNAME
	fi


	if id -u $USERNAME >/dev/null 2>&1; then
	    echo "user $USERNAME exists."
	else
	    echo "user $USERNAME does not exist. adding."
	    $USERADD  $USERNAME -g $USERNAME -m -s /bin/bash 
	fi
}



do_db() {



    db_input high openinfoman/dbname || true
    db_go || true
    db_get openinfoman/dbname || true
    DBNAME="$RET"

    set +e
    $BASEX -Vc "list $DBNAME" > /dev/null
    set -e
    if [ $? -eq 0 ]; then
	echo "BaseX Database $DBNAME exists\n"
    else
	echo "BaseX Database $DBNAME does not exist\n"
	$BASEX -Vc "create database $DBNAME"
    fi


}



case "$ACTION" in
    install)
	do_user
	install_basex
	do_db
     ;;
    upgrade)
	if  dpkg --compare-versions $VERSION lt 1.4.16; then
	    install_basex
	fi
esac


exit 0




